" ********************
" Plugin settings
" ********************

" Pathogen
call pathogen#infect()
call pathogen#helptags()

" CloseTag - only load for aprropriate files
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1


" Netrw
" Prevent netrw from saving history and bookmarks
let g:netrw_dirhistmax = 0

" ********************
" Theme settings
" ********************
colorscheme molokai
set background=dark
let g:molokai_original = 0


" ********************
" Misc vim settings
" ********************

" Make Vim more useful
set nocompatible

" Change mapleader
let mapleader=","

" Enable line numbers
set number

" Make tabs as wide as four spaces
set tabstop=4
" Indenting a line with >> or << will indent or un-indent by 4
set shiftwidth=4

" Enable syntax highlighting
syntax on

" Show the cursor position
set ruler

" Show the current mode
set showmode

" Highlight current line
set cursorline

" highlight matching [{()}]
set showmatch

" Searching
" search as characters are entered
set incsearch
" highlight matches
set hlsearch
" Ignore case when searching
set ignorecase
" ...unless there's a capital letter in the query
set smartcase
" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

" Centralize backups, swapfiles and undo history
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
	set undodir=~/.vim/undo
endif

" Automatic commands
if has("autocmd")
	" Enable file type detection and sets filetype-specific indetation
	filetype indent on
	" Treat .json files as .js
	autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript
	" Treat .md files as Markdown
	autocmd BufNewFile,BufRead *.md setlocal filetype=markdown
endif
