" ********************
" Plugin settings
" ********************

" Pathogen
call pathogen#infect()
call pathogen#helptags()

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1

" Ctrl+n toggles NerdTree
map <C-n> :NERDTreeToggle<CR>

" Opens NerdTree automatically when vim starts up and no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" ********************
" Theme settings
" ********************
set t_Co=256
set background=dark
colorscheme seti

" ********************
" Key mappings
" ********************

" Rolling from j to k equals ESCAPE
inoremap jk <ESC>

let mapleader = "\<Space>"

" Map ctrl+movement keys to ctrl+w followed by the movement key.
" Makes switching between split windows extremely simple.
map <C-J> <C-W>j
map <C-K> <C-W>k
map <C-H> <C-W>h
map <C-L> <C-W>l
" Map alt+movement keys to ctrl+w followed by the movement key.
" Makes moving windows much simpler.
map ∆ <C-W>J
map ˚ <C-W>K
map ˙ <C-W>H
map ¬ <C-W>L
" Map arrow keys to window resize commands.
map <Right> 5<C-W>>
map <Left> 5<C-W><
map <Up> 5<C-W>+
map <Down> 5<C-W>-

" When pressing enter it will also run :noh to turn off highlights from previous search.
nnoremap <CR> :noh<CR>


" ********************
" Misc vim settings
" ********************

" Make Vim more useful
set nocompatible

" Enable line numbers
set number

" Make tabs as wide as four spaces
set tabstop=4
" Indenting a line with >> or << will indent or un-indent by 4
set shiftwidth=4

" Enable syntax highlighting
syntax on

" Show the cursor position
set ruler

" Allow background buffers
set hidden

" Show the current mode
set showmode

" Highlight current line
set cursorline

" highlight matching [{()}]
set showmatch

" Searching
" search as characters are entered
set incsearch
" highlight matches
set hlsearch
" Ignore case when searching
set ignorecase
" ...unless there's a capital letter in the query
set smartcase

" ********************
" Encoding
" ********************
set encoding=utf-8




" Centralize backups, swapfiles and undo history
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
	set undodir=~/.vim/undo
endif

" Automatic commands
if has("autocmd")
	" Enable file type detection and sets filetype-specific indetation
	" Allow vim to load plugins related to the detected file type.
	filetype plugin indent on
	set autoindent
	" Treat .json files as .js
	autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript
	" Treat .md files as Markdown
	autocmd BufNewFile,BufRead *.md setlocal filetype=markdown
endif
