" ********************
" Plugin settings
" ********************

" Pathogen
call pathogen#infect()
call pathogen#helptags()

" CloseTag - only load for aprropriate files
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim


" ********************
" Theme settings
" ********************
colorscheme molokai
set background=dark
let g:molokai_original = 0


